favicon: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.1638298
color:
  saturation: 0.3276596
  brandStrength: 0.4553191
  lightness: 0.4574468
  brandColors:
    - '#040F1E'
    - '#92B3D8'
    - '#E0E8E9'
    - '#FFBD91'
    - '#C6786E'
  rhythmicContrast: 0.312766
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
layout_spectrum: 1
name: make or brake the grid
