typography_spectrum: 0.1638298
color:
  brandColors:
    - '#FFFFFF'
    - '#6990D1'
    - '#0C0D10'
    - '#CFB697'
    - '#FFFF02'
  brandStrength: 0.4553191
  lightness: 0.5723404
  saturation: 0.4553191
  rhythmicContrast: 0.2638298
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75317
analytics:
  google: null
  facebook: null
  twitter: null
name: make or brake the grid
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Hello new editor
description: 'all in place, hä?'
purpose: []
