name: make or brake the grid
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#040F1E'
    - '#92B3D8'
    - '#E0E8E9'
    - '#FFBD91'
    - '#C6786E'
  lightness: 1
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
typography_spectrum: 0.1638298
