favicon: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.1638298
color:
  saturation: 0.4553191
  brandStrength: 0.4553191
  lightness: 0.5723404
  brandColors:
    - '#FFFFFF'
    - '#6990D1'
    - '#0C0D10'
    - '#CFB697'
    - '#FFFF02'
  rhythmicContrast: 0.2638298
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: make or brake the grid
