layout_spectrum: 0.7061595155391842
typography_spectrum: 0.021389372879639268
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.6317492229864001
  lightness: 0.357139278203249
  saturation: 0.26300889858976007
  rhythmicContrast: 0.9970667923334986
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: make or brake the grid
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Ready
    id: 867e8b26-3290-44ce-a5ca-633dbc7f8193
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Hello new editor
description: 'all in place, hä?'
purpose: []
